package com.anegr.dao;

import com.anegr.domain.Poem;
import com.anegr.domain.PoemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PoemMapper extends BaseDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int countByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int deleteByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int insert(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int insertSelective(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    List<Poem> selectByExampleWithBLOBs(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    List<Poem> selectByExample(PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    Poem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") Poem record, @Param("example") PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") Poem record, @Param("example") PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByExample(@Param("record") Poem record, @Param("example") PoemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByPrimaryKeySelective(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(Poem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Aug 08 15:58:48 CST 2017
     */
    int updateByPrimaryKey(Poem record);
    
    void deleteBatch(List list);
    
    int countForSearch(PoemExample example);
    
    List pagingQueryForSearch(PaginatorEx paginatorex);    
}