package com.anegr.domain;

import java.util.Date;

public class Poem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.poet_id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Integer poetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.title
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poetries.content
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Poem(Integer id, Integer poetId, String title, Date createdAt, Date updatedAt, String content) {
        this.id = id;
        this.poetId = poetId;
        this.title = title;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.content = content;
    }

    public Poem(Integer id, Integer poetId, String title, Date createdAt, Date updatedAt) {
		super();
		this.id = id;
		this.poetId = poetId;
		this.title = title;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poetries
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Poem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.id
     *
     * @return the value of poetries.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.id
     *
     * @param id the value for poetries.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.poet_id
     *
     * @return the value of poetries.poet_id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Integer getPoetId() {
        return poetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.poet_id
     *
     * @param poetId the value for poetries.poet_id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setPoetId(Integer poetId) {
        this.poetId = poetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.title
     *
     * @return the value of poetries.title
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.title
     *
     * @param title the value for poetries.title
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.created_at
     *
     * @return the value of poetries.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.created_at
     *
     * @param createdAt the value for poetries.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.updated_at
     *
     * @return the value of poetries.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.updated_at
     *
     * @param updatedAt the value for poetries.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poetries.content
     *
     * @return the value of poetries.content
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poetries.content
     *
     * @param content the value for poetries.content
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}