package com.anegr.domain;

import java.util.Date;

public class Poet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poets.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poets.name
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poets.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column poets.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poets
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Poet(Integer id, String name, Date createdAt, Date updatedAt) {
        this.id = id;
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table poets
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Poet() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poets.id
     *
     * @return the value of poets.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poets.id
     *
     * @param id the value for poets.id
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poets.name
     *
     * @return the value of poets.name
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poets.name
     *
     * @param name the value for poets.name
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poets.created_at
     *
     * @return the value of poets.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poets.created_at
     *
     * @param createdAt the value for poets.created_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column poets.updated_at
     *
     * @return the value of poets.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column poets.updated_at
     *
     * @param updatedAt the value for poets.updated_at
     *
     * @mbggenerated Tue Apr 11 09:00:54 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}